NAME : BALKARAN SINGH
BATCH : 2Q11
ROLL NO : 102317009

ASSIGNMENT - 1 [NUMPY]

Q1: Questions on Basic NumPy Array

In [3]:
import numpy as np
from collections import Counter

print("Q1:")

# (a)
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) Reversed array:", arr[::-1])

# (b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("b1) Flatten using flatten():", array1.flatten())
print("b2) Flatten using ravel():", array1.ravel())

# (c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("c) Arrays are equal:", np.array_equal(arr1, arr2))

# (d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq_x = Counter(x).most_common(1)[0]
freq_y = Counter(y).most_common(1)[0]
print(f"d1) Most frequent in x: {freq_x[0]} at indices {np.where(x == freq_x[0])[0]}")
print(f"d2) Most frequent in y: {freq_y[0]} at indices {np.where(y == freq_y[0])[0]}")

# (e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("e1) Sum of all elements:", gfg.sum())
print("e2) Row-wise sum:", gfg.sum(axis=1))
print("e3) Column-wise sum:", gfg.sum(axis=0))

# (f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("f1) Diagonal sum:", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("f2) Eigenvalues:", eig_vals)
print("f3) Eigenvectors:\n", eig_vecs)
print("f4) Inverse:\n", np.linalg.inv(n_array))
print("f5) Determinant:", np.linalg.det(n_array))

# (g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("g1) Matrix product 1:\n", np.dot(p1, q1))
print("g1) Covariance 1:\n", np.cov(p1.flatten(), q1.flatten()))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("g2) Matrix product 2:\n", np.dot(p2, q2))
print("g2) Covariance 2:\n", np.cov(p2.flatten(), q2.flatten()))

# (h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("h1) Inner product:\n", np.inner(x, y))
print("h2) Outer product:\n", np.outer(x, y))
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("h3) Cartesian product:\n", cartesian)


Q1:
a) Reversed array: [5 4 6 3 2 1]
b1) Flatten using flatten(): [1 2 3 2 4 5 1 2 3]
b2) Flatten using ravel(): [1 2 3 2 4 5 1 2 3]
c) Arrays are equal: True
d1) Most frequent in x: 1 at indices [0 5 7 8 9]
d2) Most frequent in y: 1 at indices [0 1 2]
e1) Sum of all elements: 45
e2) Row-wise sum: [[14]
 [16]
 [15]]
e3) Column-wise sum: [[20  9 16]]
f1) Diagonal sum: 176
f2) Eigenvalues: [98.16835147 28.097044   49.73460452]
f3) Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
f4) Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
f5) Determinant: 137180.0000000001
g1) Matrix product 1:
 [[16 19]
 [26 31]]
g1) Covariance 1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
g2) Matrix product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
g2) Covariance 2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
h1) Inner product:
 [[17 

Q2: Based on NumPy Mathematics and Statistics

In [4]:
print("\nQ2:")

# (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("a1) Absolute values:\n", np.abs(array))

# Percentiles
flat = array.flatten()
print("a2) Percentiles (flat):", np.percentile(flat, [25, 50, 75]))
print("a2) Percentiles (cols):\n", np.percentile(array, [25, 50, 75], axis=0))
print("a2) Percentiles (rows):\n", np.percentile(array, [25, 50, 75], axis=1))

# Mean, Median, Std
print("a3) Mean (flat):", np.mean(flat))
print("a3) Median (flat):", np.median(flat))
print("a3) Std (flat):", np.std(flat))

print("a3) Mean (cols):", np.mean(array, axis=0))
print("a3) Median (cols):", np.median(array, axis=0))
print("a3) Std (cols):", np.std(array, axis=0))

print("a3) Mean (rows):", np.mean(array, axis=1))
print("a3) Median (rows):", np.median(array, axis=1))
print("a3) Std (rows):", np.std(array, axis=1))

# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("b1) Floor:", np.floor(a))
print("b2) Ceil:", np.ceil(a))
print("b3) Trunc:", np.trunc(a))
print("b4) Rounded:", np.round(a))



Q2:
a1) Absolute values:
 [[1 2 3]
 [4 5 6]]
a2) Percentiles (flat): [-3.5 -0.5  2.5]
a2) Percentiles (cols):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
a2) Percentiles (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
a3) Mean (flat): -0.5
a3) Median (flat): -0.5
a3) Std (flat): 3.8622100754188224
a3) Mean (cols): [-1.5  1.5 -1.5]
a3) Median (cols): [-1.5  1.5 -1.5]
a3) Std (cols): [2.5 3.5 4.5]
a3) Mean (rows): [ 0.66666667 -1.66666667]
a3) Median (rows): [ 1. -4.]
a3) Std (rows): [2.05480467 4.78423336]
b1) Floor: [-2. -2. -1.  0.  1.  1.  3.]
b2) Ceil: [-1. -1. -0.  1.  2.  2.  3.]
b3) Trunc: [-1. -1. -0.  0.  1.  1.  3.]
b4) Rounded: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

In [5]:
print("\nQ3:")

# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("a1) Sorted array:", np.sort(array))
print("a2) Indices of sorted array:", np.argsort(array))
print("a3) 4 smallest:", np.sort(array)[:4])
print("a4) 5 largest:", np.sort(array)[-5:])

# (b)
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array_b[array_b == array_b.astype(int)]
float_elements = array_b[array_b != array_b.astype(int)]
print("b1) Integer elements only:", int_elements)
print("b2) Float elements only:", float_elements)



Q3:
a1) Sorted array: [ 10  16  16  52  54  62 453]
a2) Indices of sorted array: [0 3 4 1 5 2 6]
a3) 4 smallest: [10 16 16 52]
a4) 5 largest: [ 16  52  54  62 453]
b1) Integer elements only: [1. 2. 3. 2.]
b2) Float elements only: [1.2 2.2]


Q4:

In [6]:
from PIL import Image
print("\nQ4:")

# (a) Save image array to file
def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if len(img_array.shape) == 2:
        np.savetxt("greyscale_image.txt", img_array, fmt='%d')
        print("a) Greyscale image saved to greyscale_image.txt")
    else:
        for i in range(img_array.shape[2]):
            np.savetxt(f"rgb_channel_{i}.txt", img_array[:, :, i], fmt='%d')
        print("a) RGB image saved to rgb_channel_0.txt / 1 / 2")
    return img_array

# (b) Load file from disk
def load_from_file(path):
    data = np.loadtxt(path, dtype=int)
    print(f"b) Loaded data from {path}:\n", data)
    return data



Q4:
